/* Blood Boss Log enhancements */
(()=>{const X={accounts:[],favorites:[],goals:[],achievements:[],activity:[],tab:null};
const labels={admin:'Admin',officer:'Battle',member:'Member',viewer:'Membro'};window.roleLabel=r=>labels[String(r||'').toLowerCase()]||String(r||'');
const isAdmin=()=>S.profile&&String(S.profile.role).toLowerCase()==='admin';const own=n=>X.accounts.some(a=>a.active&&a.nickname.toLowerCase()===String(n).toLowerCase());const fav=n=>X.favorites.some(f=>f.nickname.toLowerCase()===String(n).toLowerCase());
async function extLoad(){if(!S.profile)return;const queries=[sb.from('player_accounts').select('*').order('is_primary',{ascending:false}),sb.from('favorites').select('*'),sb.from('goals').select('*').eq('active',true).order('sort_order'),sb.from('achievements').select('*').eq('active',true).order('sort_order'),sb.from('public_activity').select('*').order('created_at',{ascending:false}).limit(30)];const rs=await Promise.all(queries);[X.accounts,X.favorites,X.goals,X.achievements,X.activity]=rs.map(x=>x.data||[]);}
const oldAccept=accept;accept=async session=>{const ok=await oldAccept(session);if(ok){$('#urole').textContent=roleLabel(S.profile.role);await extLoad();nav();render();addAdminTools()}return ok};
const oldLoad=load;load=async()=>{await oldLoad();try{await extLoad()}catch(e){console.warn(e)}if(['myProfile','rankings','compare','goals','achievements','activity'].includes(S.tab))render()};
const oldNav=nav;nav=()=>{oldNav();const n=$('#nav');if(!n||!S.profile)return;const extras=[['myProfile','Meu Perfil'],['rankings','Rankings'],['compare','Comparar'],['goals','Metas'],['achievements','Conquistas'],['activity','Atividades']];const hunt=[...n.querySelectorAll('[data-t]')].find(x=>x.dataset.t==='hunt');extras.forEach(([id,label])=>{if(n.querySelector(`[data-t="${id}"]`))return;const b=document.createElement('button');b.className='tab'+(S.tab===id?' active':'');b.dataset.t=id;b.textContent=label;b.onclick=()=>{S.tab=id;nav();render()};n.insertBefore(b,hunt||null)})};
function num(v){return parseFloat(String(v||0).replace('k','').replace('-',''))||0}function cards(items){return `<div class="grid">${items.map(x=>`<article class="card"><b>${esc(x[0])}</b><div class="timer ${x[2]||''}">${esc(x[1])}</div></article>`).join('')}</div>`}
function profileView(){const mine=S.scores.filter(x=>own(x.player)),b=mine.reduce((a,x)=>a+num(x.blue),0),r=mine.reduce((a,x)=>a+num(x.red),0);return title()+cards([['Contas vinculadas',String(X.accounts.filter(x=>x.active).length)],['Roubado hoje',b.toFixed(1)+'k','blue'],['Perdido hoje',r.toFixed(1)+'k','red'],['Saldo',(b-r).toFixed(1)+'k']])+`<h2>Minhas contas</h2><div class="combat">${mine.map(x=>`<div class="row"><span class="player">${esc(x.player)} <span class="rookie-badge">EU</span></span><span class="stats"><b class="blue">${esc(x.blue)}</b><b class="red">${esc(x.red)}</b></span></div>`).join('')||'<p>Nenhuma conta vinculada.</p>'}</div>`}
function rankingsView(){const rows=[...S.scores].sort((a,b)=>num(b.blue)-num(a.blue));return title()+`<div class="filters"><button class="filter-btn active">Hoje</button><button class="filter-btn">7 dias</button><button class="filter-btn">Mês</button></div><div class="combat">${rows.map((x,i)=>`<div class="row"><span class="rank">${i+1}º</span><span class="player">${esc(x.player)}${own(x.player)?' <span class="rookie-badge">EU</span>':''}</span><span class="stats"><b class="blue">${esc(x.blue)}</b><b class="red">${esc(x.red)}</b></span></div>`).join('')}</div>`}
function compareView(){return title()+`<p class="sub">Selecione contas usando Ctrl ou Command.</p><select id="cmp" multiple style="width:100%;min-height:180px;background:#111;color:#fff;border:1px solid #333;padding:10px">${S.scores.map(x=>`<option>${esc(x.player)}</option>`).join('')}</select><button id="cmpBtn" class="btn blue" style="margin-top:10px">Comparar</button><div id="cmpOut"></div>`}
function simpleList(items,renderItem){return title()+`<div class="combat">${items.map(renderItem).join('')||'<p>Nenhum item.</p>'}</div>`}
const oldRender=render;render=()=>{if(S.tab==='myProfile'){$('#main').innerHTML=profileView();return}if(S.tab==='rankings'){$('#main').innerHTML=rankingsView();return}if(S.tab==='compare'){$('#main').innerHTML=compareView();$('#cmpBtn').onclick=()=>{const names=[...$('#cmp').selectedOptions].map(x=>x.value);$('#cmpOut').innerHTML='<div class="combat" style="margin-top:15px">'+S.scores.filter(x=>names.includes(x.player)).map(x=>`<div class="row"><span class="player">${esc(x.player)}</span><span class="stats"><b class="blue">${esc(x.blue)}</b><b class="red">${esc(x.red)}</b></span></div>`).join('')+'</div>'};return}if(S.tab==='goals'){$('#main').innerHTML=simpleList(X.goals,g=>`<div class="row"><span class="player">🎯 ${esc(g.title)}<small class="sub"> ${esc(g.description||'')}</small></span><b class="blue">${esc(g.target_k)}k</b></div>`);return}if(S.tab==='achievements'){$('#main').innerHTML=simpleList(X.achievements,a=>`<div class="row"><span class="rank">${esc(a.icon||'🏆')}</span><span class="player">${esc(a.title)}<small class="sub"> ${esc(a.description||'')}</small></span><b>${esc(a.threshold_k)}k</b></div>`);return}if(S.tab==='activity'){$('#main').innerHTML=simpleList(X.activity,a=>`<div class="row"><span class="player">${esc(a.actor_name)} <span class="role">${esc(a.actor_role)}</span> ${esc(a.action)} ${esc(a.entity_name)}</span><small>${new Date(a.created_at).toLocaleString(S.lang)}</small></div>`);return}oldRender();decorate()};
function decorate(){document.querySelectorAll('.row .player,.online-item span:nth-child(2)').forEach(el=>{const n=el.firstChild&&el.firstChild.textContent.trim();if(n&&own(n)&&!el.querySelector('.my-badge')){const b=document.createElement('span');b.className='rookie-badge my-badge';b.textContent='EU';el.appendChild(b)}if(n&&fav(n)&&!el.textContent.includes('★'))el.insertAdjacentText('afterbegin','★ ')})}
function addAdminTools(){if(!isAdmin()||$('#extAdmin'))return;const d=$('#admin'),box=document.createElement('div');box.id='extAdmin';box.className='group';box.innerHTML=`<h3>Vincular contas</h3><div class="field"><label>ID do usuário no Supabase</label><input id="paUser"></div><div class="field"><label>Nicks separados por vírgula</label><input id="paNicks"></div><button id="paSave" class="btn green">Vincular</button><h3 style="margin-top:20px">Nova conquista</h3><input id="acTitle" placeholder="Título"><input id="acValue" type="number" placeholder="Valor em k" style="margin-top:8px"><button id="acSave" class="btn green" style="margin-top:8px">Criar conquista</button><h3 style="margin-top:20px">Nova meta</h3><input id="goTitle" placeholder="Título"><input id="goValue" type="number" placeholder="Valor em k" style="margin-top:8px"><button id="goSave" class="btn green" style="margin-top:8px">Criar meta</button>`;d.appendChild(box);$('#paSave').onclick=async()=>{const uid=$('#paUser').value.trim(),nicks=$('#paNicks').value.split(',').map(x=>x.trim()).filter(Boolean);const {data}=await sb.auth.getUser();const rows=nicks.map(n=>({user_id:uid,nickname:n,created_by:data.user.id,updated_by:data.user.id}));const {error}=await sb.from('player_accounts').upsert(rows,{onConflict:'nickname'});alert(error?error.message:'Contas vinculadas');await extLoad()};$('#acSave').onclick=async()=>{const {data}=await sb.auth.getUser(),{error}=await sb.from('achievements').insert({title:$('#acTitle').value,threshold_k:+$('#acValue').value,created_by:data.user.id,updated_by:data.user.id});alert(error?error.message:'Conquista criada');await extLoad()};$('#goSave').onclick=async()=>{const {data}=await sb.auth.getUser(),{error}=await sb.from('goals').insert({title:$('#goTitle').value,target_k:+$('#goValue').value,created_by:data.user.id,updated_by:data.user.id});alert(error?error.message:'Meta criada');await extLoad()}};
setInterval(()=>{if(S.profile)extLoad().catch(()=>{})},30000);
})();